# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ClusterVolumeSpecAccessModeAccessibilityRequirements do
  @moduledoc """
  Requirements for the accessible topology of the volume. These fields are optional. For an in-depth description of what these fields mean, see the CSI specification. 
  """

  @derive Jason.Encoder
  defstruct [
    :Requisite,
    :Preferred
  ]

  @type t :: %__MODULE__{
    :Requisite => [DockerEngineAPI.Model.Map.t] | nil,
    :Preferred => [DockerEngineAPI.Model.Map.t] | nil
  }

  def decode(value) do
    value
  end
end

