# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ContainerCreateResponse do
  @moduledoc """
  OK response to ContainerCreate operation
  """

  @derive Jason.Encoder
  defstruct [
    :Id,
    :Warnings
  ]

  @type t :: %__MODULE__{
    :Id => String.t,
    :Warnings => [String.t]
  }

  def decode(value) do
    value
  end
end

