# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.MountVolumeOptions do
  @moduledoc """
  Optional configuration for the `volume` type.
  """

  @derive Jason.Encoder
  defstruct [
    :NoCopy,
    :Labels,
    :DriverConfig
  ]

  @type t :: %__MODULE__{
    :NoCopy => boolean() | nil,
    :Labels => %{optional(String.t) => String.t} | nil,
    :DriverConfig => DockerEngineAPI.Model.MountVolumeOptionsDriverConfig.t | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:DriverConfig, :struct, DockerEngineAPI.Model.MountVolumeOptionsDriverConfig)
  end
end

