# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.NetworkConnectRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :Container,
    :EndpointConfig
  ]

  @type t :: %__MODULE__{
    :Container => String.t | nil,
    :EndpointConfig => DockerEngineAPI.Model.EndpointSettings.t | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:EndpointConfig, :struct, DockerEngineAPI.Model.EndpointSettings)
  end
end

