# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SwarmSpecCaConfig do
  @moduledoc """
  CA configuration.
  """

  @derive Jason.Encoder
  defstruct [
    :NodeCertExpiry,
    :ExternalCAs,
    :SigningCACert,
    :SigningCAKey,
    :ForceRotate
  ]

  @type t :: %__MODULE__{
    :NodeCertExpiry => integer() | nil,
    :ExternalCAs => [DockerEngineAPI.Model.SwarmSpecCaConfigExternalCasInner.t] | nil,
    :SigningCACert => String.t | nil,
    :SigningCAKey => String.t | nil,
    :ForceRotate => integer() | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:ExternalCAs, :list, DockerEngineAPI.Model.SwarmSpecCaConfigExternalCasInner)
  end
end

