# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SwarmInitRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :ListenAddr,
    :AdvertiseAddr,
    :DataPathAddr,
    :DataPathPort,
    :DefaultAddrPool,
    :ForceNewCluster,
    :SubnetSize,
    :Spec
  ]

  @type t :: %__MODULE__{
    :ListenAddr => String.t | nil,
    :AdvertiseAddr => String.t | nil,
    :DataPathAddr => String.t | nil,
    :DataPathPort => integer() | nil,
    :DefaultAddrPool => [String.t] | nil,
    :ForceNewCluster => boolean() | nil,
    :SubnetSize => integer() | nil,
    :Spec => DockerEngineAPI.Model.SwarmSpec.t | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:Spec, :struct, DockerEngineAPI.Model.SwarmSpec)
  end
end

