# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SwarmSpecTaskDefaultsLogDriver do
  @moduledoc """
  The log driver to use for tasks created in the orchestrator if unspecified by a service.  Updating this value only affects new tasks. Existing tasks continue to use their previously configured log driver until recreated. 
  """

  @derive Jason.Encoder
  defstruct [
    :Name,
    :Options
  ]

  @type t :: %__MODULE__{
    :Name => String.t | nil,
    :Options => %{optional(String.t) => String.t} | nil
  }

  def decode(value) do
    value
  end
end

