# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.TaskSpecLogDriver do
  @moduledoc """
  Specifies the log driver to use for tasks created from this spec. If not present, the default one for the swarm will be used, finally falling back to the engine default if not specified. 
  """

  @derive Jason.Encoder
  defstruct [
    :Name,
    :Options
  ]

  @type t :: %__MODULE__{
    :Name => String.t | nil,
    :Options => %{optional(String.t) => String.t} | nil
  }

  def decode(value) do
    value
  end
end

