# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.VolumeUsageData do
  @moduledoc """
  Usage details about the volume. This information is used by the `GET /system/df` endpoint, and omitted in other endpoints. 
  """

  @derive Jason.Encoder
  defstruct [
    :Size,
    :RefCount
  ]

  @type t :: %__MODULE__{
    :Size => integer(),
    :RefCount => integer()
  }

  def decode(value) do
    value
  end
end

