# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.Address do
  @moduledoc """
  Address represents an IPv4 or IPv6 IP address.
  """

  @derive Jason.Encoder
  defstruct [
    :Addr,
    :PrefixLen
  ]

  @type t :: %__MODULE__{
    :Addr => String.t | nil,
    :PrefixLen => integer() | nil
  }

  def decode(value) do
    value
  end
end

