# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.BuildInfo do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :stream,
    :error,
    :errorDetail,
    :status,
    :progress,
    :progressDetail,
    :aux
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :stream => String.t | nil,
    :error => String.t | nil,
    :errorDetail => DockerEngineAPI.Model.ErrorDetail.t | nil,
    :status => String.t | nil,
    :progress => String.t | nil,
    :progressDetail => DockerEngineAPI.Model.ProgressDetail.t | nil,
    :aux => DockerEngineAPI.Model.ImageId.t | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:errorDetail, :struct, DockerEngineAPI.Model.ErrorDetail)
     |> Deserializer.deserialize(:progressDetail, :struct, DockerEngineAPI.Model.ProgressDetail)
     |> Deserializer.deserialize(:aux, :struct, DockerEngineAPI.Model.ImageId)
  end
end

