# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ClusterVolumeSpecAccessModeCapacityRange do
  @moduledoc """
  The desired capacity that the volume should be created with. If empty, the plugin will decide the capacity. 
  """

  @derive Jason.Encoder
  defstruct [
    :RequiredBytes,
    :LimitBytes
  ]

  @type t :: %__MODULE__{
    :RequiredBytes => integer() | nil,
    :LimitBytes => integer() | nil
  }

  def decode(value) do
    value
  end
end

