# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.Commit do
  @moduledoc """
  Commit holds the Git-commit (SHA1) that a binary was built from, as reported in the version-string of external tools, such as `containerd`, or `runC`. 
  """

  @derive Jason.Encoder
  defstruct [
    :ID,
    :Expected
  ]

  @type t :: %__MODULE__{
    :ID => String.t | nil,
    :Expected => String.t | nil
  }

  def decode(value) do
    value
  end
end

