# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.DistributionInspect do
  @moduledoc """
  Describes the result obtained from contacting the registry to retrieve image metadata. 
  """

  @derive Jason.Encoder
  defstruct [
    :Descriptor,
    :Platforms
  ]

  @type t :: %__MODULE__{
    :Descriptor => DockerEngineAPI.Model.OciDescriptor.t,
    :Platforms => [DockerEngineAPI.Model.OciPlatform.t]
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:Descriptor, :struct, DockerEngineAPI.Model.OciDescriptor)
     |> Deserializer.deserialize(:Platforms, :list, DockerEngineAPI.Model.OciPlatform)
  end
end

