# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.EndpointPortConfig do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :Name,
    :Protocol,
    :TargetPort,
    :PublishedPort,
    :PublishMode
  ]

  @type t :: %__MODULE__{
    :Name => String.t | nil,
    :Protocol => String.t | nil,
    :TargetPort => integer() | nil,
    :PublishedPort => integer() | nil,
    :PublishMode => String.t | nil
  }

  def decode(value) do
    value
  end
end

