# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.EngineDescription do
  @moduledoc """
  EngineDescription provides information about an engine.
  """

  @derive Jason.Encoder
  defstruct [
    :EngineVersion,
    :Labels,
    :Plugins
  ]

  @type t :: %__MODULE__{
    :EngineVersion => String.t | nil,
    :Labels => %{optional(String.t) => String.t} | nil,
    :Plugins => [DockerEngineAPI.Model.EngineDescriptionPluginsInner.t] | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:Plugins, :list, DockerEngineAPI.Model.EngineDescriptionPluginsInner)
  end
end

