# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ErrorResponse do
  @moduledoc """
  Represents an error.
  """

  @derive Jason.Encoder
  defstruct [
    :message
  ]

  @type t :: %__MODULE__{
    :message => String.t
  }

  def decode(value) do
    value
  end
end

