# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.EventMessage do
  @moduledoc """
  EventMessage represents the information an event contains. 
  """

  @derive Jason.Encoder
  defstruct [
    :Type,
    :Action,
    :Actor,
    :scope,
    :time,
    :timeNano
  ]

  @type t :: %__MODULE__{
    :Type => String.t | nil,
    :Action => String.t | nil,
    :Actor => DockerEngineAPI.Model.EventActor.t | nil,
    :scope => String.t | nil,
    :time => integer() | nil,
    :timeNano => integer() | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:Actor, :struct, DockerEngineAPI.Model.EventActor)
  end
end

