# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.FilesystemChange do
  @moduledoc """
  Change in the container's filesystem. 
  """

  @derive Jason.Encoder
  defstruct [
    :Path,
    :Kind
  ]

  @type t :: %__MODULE__{
    :Path => String.t,
    :Kind => DockerEngineAPI.Model.ChangeType.t
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:Kind, :struct, DockerEngineAPI.Model.ChangeType)
  end
end

