# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.GenericResourcesInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :NamedResourceSpec,
    :DiscreteResourceSpec
  ]

  @type t :: %__MODULE__{
    :NamedResourceSpec => DockerEngineAPI.Model.GenericResourcesInnerNamedResourceSpec.t | nil,
    :DiscreteResourceSpec => DockerEngineAPI.Model.GenericResourcesInnerDiscreteResourceSpec.t | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:NamedResourceSpec, :struct, DockerEngineAPI.Model.GenericResourcesInnerNamedResourceSpec)
     |> Deserializer.deserialize(:DiscreteResourceSpec, :struct, DockerEngineAPI.Model.GenericResourcesInnerDiscreteResourceSpec)
  end
end

