# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.GraphDriverData do
  @moduledoc """
  Information about the storage driver used to store the container's and image's filesystem. 
  """

  @derive Jason.Encoder
  defstruct [
    :Name,
    :Data
  ]

  @type t :: %__MODULE__{
    :Name => String.t,
    :Data => %{optional(String.t) => String.t}
  }

  def decode(value) do
    value
  end
end

