# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ImageSummary do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :Id,
    :ParentId,
    :RepoTags,
    :RepoDigests,
    :Created,
    :Size,
    :SharedSize,
    :VirtualSize,
    :Labels,
    :Containers
  ]

  @type t :: %__MODULE__{
    :Id => String.t,
    :ParentId => String.t,
    :RepoTags => [String.t],
    :RepoDigests => [String.t],
    :Created => integer(),
    :Size => integer(),
    :SharedSize => integer(),
    :VirtualSize => integer() | nil,
    :Labels => %{optional(String.t) => String.t},
    :Containers => integer()
  }

  def decode(value) do
    value
  end
end

