# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ImagePruneResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :ImagesDeleted,
    :SpaceReclaimed
  ]

  @type t :: %__MODULE__{
    :ImagesDeleted => [DockerEngineAPI.Model.ImageDeleteResponseItem.t] | nil,
    :SpaceReclaimed => integer() | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:ImagesDeleted, :list, DockerEngineAPI.Model.ImageDeleteResponseItem)
  end
end

