# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ImageInspectRootFs do
  @moduledoc """
  Information about the image's RootFS, including the layer IDs. 
  """

  @derive Jason.Encoder
  defstruct [
    :Type,
    :Layers
  ]

  @type t :: %__MODULE__{
    :Type => String.t,
    :Layers => [String.t] | nil
  }

  def decode(value) do
    value
  end
end

