# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.IpamConfig do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :Subnet,
    :IPRange,
    :Gateway,
    :AuxiliaryAddresses
  ]

  @type t :: %__MODULE__{
    :Subnet => String.t | nil,
    :IPRange => String.t | nil,
    :Gateway => String.t | nil,
    :AuxiliaryAddresses => %{optional(String.t) => String.t} | nil
  }

  def decode(value) do
    value
  end
end

