# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.Ipam do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :Driver,
    :Config,
    :Options
  ]

  @type t :: %__MODULE__{
    :Driver => String.t | nil,
    :Config => [DockerEngineAPI.Model.IpamConfig.t] | nil,
    :Options => %{optional(String.t) => String.t} | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:Config, :list, DockerEngineAPI.Model.IpamConfig)
  end
end

