# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.JoinTokens do
  @moduledoc """
  JoinTokens contains the tokens workers and managers need to join the swarm. 
  """

  @derive Jason.Encoder
  defstruct [
    :Worker,
    :Manager
  ]

  @type t :: %__MODULE__{
    :Worker => String.t | nil,
    :Manager => String.t | nil
  }

  def decode(value) do
    value
  end
end

