# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.Limit do
  @moduledoc """
  An object describing a limit on resources which can be requested by a task. 
  """

  @derive Jason.Encoder
  defstruct [
    :NanoCPUs,
    :MemoryBytes,
    :Pids
  ]

  @type t :: %__MODULE__{
    :NanoCPUs => integer() | nil,
    :MemoryBytes => integer() | nil,
    :Pids => integer() | nil
  }

  def decode(value) do
    value
  end
end

