# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ManagerStatus do
  @moduledoc """
  ManagerStatus represents the status of a manager.  It provides the current status of a node's manager component, if the node is a manager. 
  """

  @derive Jason.Encoder
  defstruct [
    :Leader,
    :Reachability,
    :Addr
  ]

  @type t :: %__MODULE__{
    :Leader => boolean() | nil,
    :Reachability => DockerEngineAPI.Model.Reachability.t | nil,
    :Addr => String.t | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:Reachability, :struct, DockerEngineAPI.Model.Reachability)
  end
end

