# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.MountTmpfsOptions do
  @moduledoc """
  Optional configuration for the `tmpfs` type.
  """

  @derive Jason.Encoder
  defstruct [
    :SizeBytes,
    :Mode
  ]

  @type t :: %__MODULE__{
    :SizeBytes => integer() | nil,
    :Mode => integer() | nil
  }

  def decode(value) do
    value
  end
end

