# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.MountVolumeOptionsDriverConfig do
  @moduledoc """
  Map of driver specific options
  """

  @derive Jason.Encoder
  defstruct [
    :Name,
    :Options
  ]

  @type t :: %__MODULE__{
    :Name => String.t | nil,
    :Options => %{optional(String.t) => String.t} | nil
  }

  def decode(value) do
    value
  end
end

