# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.NetworkCreateRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :Name,
    :CheckDuplicate,
    :Driver,
    :Internal,
    :Attachable,
    :Ingress,
    :IPAM,
    :EnableIPv6,
    :Options,
    :Labels
  ]

  @type t :: %__MODULE__{
    :Name => String.t,
    :CheckDuplicate => boolean() | nil,
    :Driver => String.t | nil,
    :Internal => boolean() | nil,
    :Attachable => boolean() | nil,
    :Ingress => boolean() | nil,
    :IPAM => DockerEngineAPI.Model.Ipam.t | nil,
    :EnableIPv6 => boolean() | nil,
    :Options => %{optional(String.t) => String.t} | nil,
    :Labels => %{optional(String.t) => String.t} | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:IPAM, :struct, DockerEngineAPI.Model.Ipam)
  end
end

