# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.NetworkContainer do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :Name,
    :EndpointID,
    :MacAddress,
    :IPv4Address,
    :IPv6Address
  ]

  @type t :: %__MODULE__{
    :Name => String.t | nil,
    :EndpointID => String.t | nil,
    :MacAddress => String.t | nil,
    :IPv4Address => String.t | nil,
    :IPv6Address => String.t | nil
  }

  def decode(value) do
    value
  end
end

