# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.NetworkCreateResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :Id,
    :Warning
  ]

  @type t :: %__MODULE__{
    :Id => String.t | nil,
    :Warning => String.t | nil
  }

  def decode(value) do
    value
  end
end

