# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.NodeStatus do
  @moduledoc """
  NodeStatus represents the status of a node.  It provides the current status of the node, as seen by the manager. 
  """

  @derive Jason.Encoder
  defstruct [
    :State,
    :Message,
    :Addr
  ]

  @type t :: %__MODULE__{
    :State => DockerEngineAPI.Model.NodeState.t | nil,
    :Message => String.t | nil,
    :Addr => String.t | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:State, :struct, DockerEngineAPI.Model.NodeState)
  end
end

