# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.PluginConfigNetwork do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :Type
  ]

  @type t :: %__MODULE__{
    :Type => String.t
  }

  def decode(value) do
    value
  end
end

