# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.PluginMount do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :Name,
    :Description,
    :Settable,
    :Source,
    :Destination,
    :Type,
    :Options
  ]

  @type t :: %__MODULE__{
    :Name => String.t,
    :Description => String.t,
    :Settable => [String.t],
    :Source => String.t,
    :Destination => String.t,
    :Type => String.t,
    :Options => [String.t]
  }

  def decode(value) do
    value
  end
end

