# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.PluginConfigInterface do
  @moduledoc """
  The interface between Docker and the plugin
  """

  @derive Jason.Encoder
  defstruct [
    :Types,
    :Socket,
    :ProtocolScheme
  ]

  @type t :: %__MODULE__{
    :Types => [DockerEngineAPI.Model.PluginInterfaceType.t],
    :Socket => String.t,
    :ProtocolScheme => String.t | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:Types, :list, DockerEngineAPI.Model.PluginInterfaceType)
  end
end

