# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.PluginConfigUser do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :UID,
    :GID
  ]

  @type t :: %__MODULE__{
    :UID => integer() | nil,
    :GID => integer() | nil
  }

  def decode(value) do
    value
  end
end

