# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.PluginInterfaceType do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :Prefix,
    :Capability,
    :Version
  ]

  @type t :: %__MODULE__{
    :Prefix => String.t,
    :Capability => String.t,
    :Version => String.t
  }

  def decode(value) do
    value
  end
end

