# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.PortBinding do
  @moduledoc """
  PortBinding represents a binding between a host IP address and a host port. 
  """

  @derive Jason.Encoder
  defstruct [
    :HostIp,
    :HostPort
  ]

  @type t :: %__MODULE__{
    :HostIp => String.t | nil,
    :HostPort => String.t | nil
  }

  def decode(value) do
    value
  end
end

