# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.Port do
  @moduledoc """
  An open port on a container
  """

  @derive Jason.Encoder
  defstruct [
    :IP,
    :PrivatePort,
    :PublicPort,
    :Type
  ]

  @type t :: %__MODULE__{
    :IP => String.t | nil,
    :PrivatePort => integer(),
    :PublicPort => integer() | nil,
    :Type => String.t
  }

  def decode(value) do
    value
  end
end

