# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ResourceObject do
  @moduledoc """
  An object describing the resources which can be advertised by a node and requested by a task. 
  """

  @derive Jason.Encoder
  defstruct [
    :NanoCPUs,
    :MemoryBytes,
    :GenericResources
  ]

  @type t :: %__MODULE__{
    :NanoCPUs => integer() | nil,
    :MemoryBytes => integer() | nil,
    :GenericResources => [DockerEngineAPI.Model.GenericResourcesInner.t] | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:GenericResources, :list, DockerEngineAPI.Model.GenericResourcesInner)
  end
end

