# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ResourcesBlkioWeightDeviceInner do
  @moduledoc """

  """

  @derive Jason.Encoder
  defstruct [
    :Path,
    :Weight
  ]

  @type t :: %__MODULE__{
    :Path => String.t | nil,
    :Weight => integer() | nil
  }

  def decode(value) do
    value
  end
end
