# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ServiceEndpointVirtualIpsInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :NetworkID,
    :Addr
  ]

  @type t :: %__MODULE__{
    :NetworkID => String.t | nil,
    :Addr => String.t | nil
  }

  def decode(value) do
    value
  end
end

