# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ServiceSpecModeReplicatedJob do
  @moduledoc """
  The mode used for services with a finite number of tasks that run to a completed state. 
  """

  @derive Jason.Encoder
  defstruct [
    :MaxConcurrent,
    :TotalCompletions
  ]

  @type t :: %__MODULE__{
    :MaxConcurrent => integer() | nil,
    :TotalCompletions => integer() | nil
  }

  def decode(value) do
    value
  end
end

