# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.ServiceUpdateResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :Warnings
  ]

  @type t :: %__MODULE__{
    :Warnings => [String.t] | nil
  }

  def decode(value) do
    value
  end
end

