# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SwarmSpecOrchestration do
  @moduledoc """
  Orchestration configuration.
  """

  @derive Jason.Encoder
  defstruct [
    :TaskHistoryRetentionLimit
  ]

  @type t :: %__MODULE__{
    :TaskHistoryRetentionLimit => integer() | nil
  }

  def decode(value) do
    value
  end
end

