# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SwarmSpecEncryptionConfig do
  @moduledoc """
  Parameters related to encryption-at-rest.
  """

  @derive Jason.Encoder
  defstruct [
    :AutoLockManagers
  ]

  @type t :: %__MODULE__{
    :AutoLockManagers => boolean() | nil
  }

  def decode(value) do
    value
  end
end

