# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SwarmInfo do
  @moduledoc """
  Represents generic information about swarm. 
  """

  @derive Jason.Encoder
  defstruct [
    :NodeID,
    :NodeAddr,
    :LocalNodeState,
    :ControlAvailable,
    :Error,
    :RemoteManagers,
    :Nodes,
    :Managers,
    :Cluster
  ]

  @type t :: %__MODULE__{
    :NodeID => String.t | nil,
    :NodeAddr => String.t | nil,
    :LocalNodeState => DockerEngineAPI.Model.LocalNodeState.t | nil,
    :ControlAvailable => boolean() | nil,
    :Error => String.t | nil,
    :RemoteManagers => [DockerEngineAPI.Model.PeerNode.t] | nil,
    :Nodes => integer() | nil,
    :Managers => integer() | nil,
    :Cluster => DockerEngineAPI.Model.ClusterInfo.t | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:LocalNodeState, :struct, DockerEngineAPI.Model.LocalNodeState)
     |> Deserializer.deserialize(:RemoteManagers, :list, DockerEngineAPI.Model.PeerNode)
     |> Deserializer.deserialize(:Cluster, :struct, DockerEngineAPI.Model.ClusterInfo)
  end
end

