# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.SystemInfoDefaultAddressPoolsInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :Base,
    :Size
  ]

  @type t :: %__MODULE__{
    :Base => String.t | nil,
    :Size => integer() | nil
  }

  def decode(value) do
    value
  end
end

