# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.TaskSpecContainerSpecPrivileges do
  @moduledoc """
  Security options for the container
  """

  @derive Jason.Encoder
  defstruct [
    :CredentialSpec,
    :SELinuxContext
  ]

  @type t :: %__MODULE__{
    :CredentialSpec => DockerEngineAPI.Model.TaskSpecContainerSpecPrivilegesCredentialSpec.t | nil,
    :SELinuxContext => DockerEngineAPI.Model.TaskSpecContainerSpecPrivilegesSeLinuxContext.t | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:CredentialSpec, :struct, DockerEngineAPI.Model.TaskSpecContainerSpecPrivilegesCredentialSpec)
     |> Deserializer.deserialize(:SELinuxContext, :struct, DockerEngineAPI.Model.TaskSpecContainerSpecPrivilegesSeLinuxContext)
  end
end

