# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.TaskSpecContainerSpecPrivilegesSeLinuxContext do
  @moduledoc """
  SELinux labels of the container
  """

  @derive Jason.Encoder
  defstruct [
    :Disable,
    :User,
    :Role,
    :Type,
    :Level
  ]

  @type t :: %__MODULE__{
    :Disable => boolean() | nil,
    :User => String.t | nil,
    :Role => String.t | nil,
    :Type => String.t | nil,
    :Level => String.t | nil
  }

  def decode(value) do
    value
  end
end

