# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.TaskSpecContainerSpecSecretsInnerFile do
  @moduledoc """
  File represents a specific target that is backed by a file. 
  """

  @derive Jason.Encoder
  defstruct [
    :Name,
    :UID,
    :GID,
    :Mode
  ]

  @type t :: %__MODULE__{
    :Name => String.t | nil,
    :UID => String.t | nil,
    :GID => String.t | nil,
    :Mode => integer() | nil
  }

  def decode(value) do
    value
  end
end

