# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.TaskSpecContainerSpecPrivilegesCredentialSpec do
  @moduledoc """
  CredentialSpec for managed service account (Windows only)
  """

  @derive Jason.Encoder
  defstruct [
    :Config,
    :File,
    :Registry
  ]

  @type t :: %__MODULE__{
    :Config => String.t | nil,
    :File => String.t | nil,
    :Registry => String.t | nil
  }

  def decode(value) do
    value
  end
end

