# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.TaskStatus do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :Timestamp,
    :State,
    :Message,
    :Err,
    :ContainerStatus
  ]

  @type t :: %__MODULE__{
    :Timestamp => String.t | nil,
    :State => DockerEngineAPI.Model.TaskState.t | nil,
    :Message => String.t | nil,
    :Err => String.t | nil,
    :ContainerStatus => DockerEngineAPI.Model.TaskStatusContainerStatus.t | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:State, :struct, DockerEngineAPI.Model.TaskState)
     |> Deserializer.deserialize(:ContainerStatus, :struct, DockerEngineAPI.Model.TaskStatusContainerStatus)
  end
end

