# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.TaskStatusContainerStatus do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :ContainerID,
    :PID,
    :ExitCode
  ]

  @type t :: %__MODULE__{
    :ContainerID => String.t | nil,
    :PID => integer() | nil,
    :ExitCode => integer() | nil
  }

  def decode(value) do
    value
  end
end

