# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.VolumePruneResponse do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :VolumesDeleted,
    :SpaceReclaimed
  ]

  @type t :: %__MODULE__{
    :VolumesDeleted => [String.t] | nil,
    :SpaceReclaimed => integer() | nil
  }

  def decode(value) do
    value
  end
end

