# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.Volume do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :Name,
    :Driver,
    :Mountpoint,
    :CreatedAt,
    :Status,
    :Labels,
    :Scope,
    :ClusterVolume,
    :Options,
    :UsageData
  ]

  @type t :: %__MODULE__{
    :Name => String.t,
    :Driver => String.t,
    :Mountpoint => String.t,
    :CreatedAt => String.t | nil,
    :Status => %{optional(String.t) => map()} | nil,
    :Labels => %{optional(String.t) => String.t},
    :Scope => String.t,
    :ClusterVolume => DockerEngineAPI.Model.ClusterVolume.t | nil,
    :Options => %{optional(String.t) => String.t},
    :UsageData => DockerEngineAPI.Model.VolumeUsageData.t | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:ClusterVolume, :struct, DockerEngineAPI.Model.ClusterVolume)
     |> Deserializer.deserialize(:UsageData, :struct, DockerEngineAPI.Model.VolumeUsageData)
  end
end

