# NOTE: This file is auto generated by OpenAPI Generator 7.0.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule DockerEngineAPI.Model.VolumeListResponse do
  @moduledoc """
  Volume list response
  """

  @derive Jason.Encoder
  defstruct [
    :Volumes,
    :Warnings
  ]

  @type t :: %__MODULE__{
    :Volumes => [DockerEngineAPI.Model.Volume.t] | nil,
    :Warnings => [String.t] | nil
  }

  alias DockerEngineAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:Volumes, :list, DockerEngineAPI.Model.Volume)
  end
end

